name: Maven Build

on:
  pull_request:
    branches: [ "staging" , "main" ]
  push:
    branches: [ "staging", "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '16'
          distribution: 'temurin'
      - name: compile code
        run: mvn compile
